### ISSUE TITLE
Problem with get_features in train.py

### ISSUE THREAD

**Issue by Elehrer** [hls-fpga-machine-learning/keras-training#8]
I have been following the installation guidlines and have just gotten to testing, but when I run the line "python train.py -t t_allpar_new -i ../data/processed-pythia82-lhc13-all-pt1-50k-r1_h022_e0175_t220_nonu_truth.z -c train_config_threelayer.yml -o train_simple/" from inside the /keras-training/train directory, I get the following error that I have tried to fix a dozen different ways to no avail. What is going on here?

```
 (tensorflow) bash-4.1$ python train.py -t t_allpar_new -i ../data/processed-pythia82-lhc13-all-pt1-50k-r1_h022_e0175_t220_nonu_truth.z -c train_config_threelayer.yml -o train_simple/
Using TensorFlow backend.
Loading configuration from train_config_threelayer.yml
Traceback (most recent call last):
  File "train.py", line 139, in <module>
    X_train_val, X_test, y_train_val, y_test, labels  = get_features(options, yamlConfig)
  File "train.py", line 35, in get_features
    treeArray = h5File[options.tree][()]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/uscms/home/elehrer/nobackup/anaconda2/envs/tensorflow/lib/python2.7/site-packages/h5py/_hl/group.py", line 177, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 190, in h5py.h5o.open
KeyError: "Unable to open object (object 't_allpar_new' doesn't exist)"
```

**Comment by jmduarte** [comment]
Hi,

Somehow I think the file numpy array file got corrupted.. I updated the file here in the README: 75182c37afd6d2e41681b92e5d9ecc61181e4ac8
